name = "property-paradise"
compatibility_date = "2026-08-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "property_paradise_db"
database_id = "ef2812b5-66c1-4a99-b484-acf6423163e5"
